services:
  # Database section

  # orderdb: sqlserverdb    
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"

  # productdb: mysqldb 
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # customerdb: postgresdb
  customerdb:
    container_name: customerdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # basketdb: redis    
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  # inventorydb: mongodb 
  inventorydb:
    container_name: inventorydb
    restart: always
    volumes:
      - mongo_data:/data/lib
    ports:
      - "27017:27017"

# infractructure section

  # rabbitmq
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # pgadmin  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=10a11ngominh@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"

  # portainer
  portainer:
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8080:8000"
      - "9000:9000"

  # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/urs/share/elasticsearch/data
    ports:
      - "9200:9200"

  # kibana
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"